### ISSUE TITLE
Cannot Install Plugin on Self-Hosted Discourse server - rbsecp256k1

### ISSUE THREAD

**Issue by Sterahi** [spruceid/discourse-siwe-auth#15]
Using the latest docker image from Discourse we're seeing the error: 
```
I, [2022-05-20T16:58:42.288275 #1]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake db:migrate'
ERROR:  Error installing rbsecp256k1:
	ERROR: Failed to build gem native extension.

    current directory: /var/www/discourse/plugins/discourse-siwe-auth/gems/2.7.6/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r ./siteconf20220520-1530-cv5chg.rb extconf.rb
Downloading libsecp256k1.zip (100%)
```
Even after installing the required system-level dependencies of rbsecp256k1 our discourse server will not start. Our app.yml looks like: 

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/spruceid/discourse-siwe-auth.git
```

Any assistance would be appreciated!

**Comment by obstropolos** [comment]
> Just an update, after re-testing today I can confirm that the changes made [here](https://github.com/discourse/discourse/pull/16176) did not resolve the issue we're having.

Thanks for the heads up - we're looking into this.

**Comment by miguelmota** [comment]
Hi, is there any update on this issue?

![DeepinScreenshot_select-area_20220613213153](https://user-images.githubusercontent.com/168240/173493798-44c44095-754b-4451-b1a7-47a205a7e589.png)

**Comment by burningtree** [comment]
I have the same problem:
```
ERROR:  Error installing rbsecp256k1:
	ERROR: Failed to build gem native extension.
```

Im using:
- Ubuntu 22.04 LTS
- Docker version 20.10.17

**Comment by zashton** [comment]
> > Just an update, after re-testing today I can confirm that the changes made [here](https://github.com/discourse/discourse/pull/16176) did not resolve the issue we're having.
> 
> Thanks for the heads up - we're looking into this.

any luck on this issue ? 
trying for the first time on a fresh installation of discourse and couldn't install the plugin at all

**Comment by obstropolos** [comment]
Still trying to find the root cause here, thanks again for your patience all -

**Comment by communiteq** [comment]
All you need to do is add the `before_code `lines to app.yml to make sure the rubyzip gem is installed.
I don't know how to fix this _within_ the plugin though.

```
hooks:
  before_code:
    - exec:
        cmd:
          - gem install rubyzip
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/spruceid/discourse-siwe-auth
```
